apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webserver-deployment
  labels:
    app: simple-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webserver
  template:
    metadata:
      labels:
        app: simple-webserver
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-mycluster-server-0
      volumes:
        - name: myhostvolume
          hostPath:
            path: /src
            type: Directory    
      containers:
      - name: simple-webserver
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
         - name: myhostvolume
           mountPath: /usr/share/nginx/html       
