apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webserver-deployment
  labels:
    app: simple-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webserver
  template:
    metadata:
      labels:
        app: simple-webserver
    spec:
      containers:
      - name: simple-webserver
        image: nginx
        ports:
        - containerPort: 80
